name: iOS Beta Release

on:
  push:
    tags:        
      - 'iOS-[0-9]+.[0-9]+.[0-9]+-RC[0-9]+'
      
jobs:
  deploy:
    name: Deploy to Testflight
    runs-on: macOS-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: eskatos/gradle-command-action@v1
        with:
         gradle-version: 5.6.2
      - uses: sinoru/actions-setup-xcode@v1.1
        with:
          xcode-version: '11.4' # Exact version of a Xcode version to use
          apple-id: ${{ secrets.APPLEID_USERNAME }} # Apple ID to download from Apple Developer when Xcode not available in local
          apple-id-password: ${{ secrets.APPLEID_PASSWORD }}
      - name: Update version
        run: |
          latest_beta="$(git describe --match "iOS*-RC*" --abbrev=0 --tags)"
          version=${latest_beta#"iOS-"}
          cd native/KotlinIOS
          xcrun agvtool new-marketing-version $version
          xcrun agvtool next-version -all
      - name: Install cocoapods
        run: |
          cd native/KotlinIOS
          sudo gem install cocoapods
          sudo bundle install
      - name: Install pods
        run: |
          cd native/KotlinIOS
          bundle exec pod install
      - name: Install gpg
        run: brew install gnupg
      - name: Setup provisioning profile
        env:
          IOS_KEYS: ${{ secrets.IOS_KEYS }}
        run: ./.github/secrets/decrypt_secrets.sh
      - name: Archiving project
        env:
          PR_NUMBER: $(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
        run: ./.github/scripts/archive_app.sh
      - name: Exporting .ipa
        run: ./.github/scripts/export_ipa.sh
      - name: Publishing app
        if: success()
        env:
          APPLEID_USERNAME: ${{ secrets.APPLEID_USERNAME }}
          APPLEID_PASSWORD: ${{ secrets.APPLEID_PASSWORD }}
        run: ./.github/scripts/publish_testflight.sh
